// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RestApi.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MovieResourceFeature : object, Xunit.IClassFixture<MovieResourceFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Movie.feature"
#line hidden
        
        public MovieResourceFeature(MovieResourceFeature.FixtureData fixtureData, RestApi_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Movie Resource", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get All Movies")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Get All Movies")]
        [Xunit.TraitAttribute("Category", "GetMovie")]
        public void GetAllMovies()
        {
            string[] tagsOfScenario = new string[] {
                    "GetMovie"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get All Movies", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
 testRunner.When("I make Get Request \'api/Movies/\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
 testRunner.Then("response code must be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 8
 testRunner.And(@"response data must look like '[{""id"":1,""name"":""Avatar"",""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate  and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":[{""id"":2,""name"":""Will Smith"",""bio"":""Steve Rogers, a scrawny but patriotic young man who is given super-soldier serum and becomes Captain America"",""dateOfBirth"":""1976-06-13T00:00:00"",""gender"":""Male""}],""genres"":[{""id"":1,""name"":""Action""}],""producer"":{""id"":1,""name"":""S.S. Rajamouli"",""bio"":""S.S. Rajamouli is an Indian film director and screenwriter who primarily works in Telugu cinema and is known for his action, fantasy, and epic genre films. He is the highest grossing Indian director of all time and the highest-paid director in India. "",""dateOfBirth"":""1973-10-20T00:00:00"",""gender"":""Male""},""poster"":""C:\\Users\\Kalyan\\Downloads\\Avatar.png""}]'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Get By Id of Movie")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Get By Id of Movie")]
        [Xunit.TraitAttribute("Category", "GetByMovieId")]
        [Xunit.InlineDataAttribute("1", "200", new string[0])]
        [Xunit.InlineDataAttribute("9", "400", new string[0])]
        public void GetByIdOfMovie(string id, string statusCode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "GetByMovieId"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Id", id);
            argumentsOfScenario.Add("status code", statusCode);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get By Id of Movie", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 13
 testRunner.When(string.Format("I make Get Request with \'{0}\' and \'api/Movies/\'", id), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 14
 testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Add a Movie")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Add a Movie")]
        [Xunit.TraitAttribute("Category", "PostMovie")]
        [Xunit.InlineDataAttribute(@"{""Name"":""Bahubali"",""YearOfRelease"":""2009-05-22T00:00:00"",""Plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""Actors"":""1"",""Genres"":""1"",""ProducerId"":1,""Poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "201", new string[0])]
        [Xunit.InlineDataAttribute(@"{""name"":,""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":""1"",""producer"":1,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        [Xunit.InlineDataAttribute(@"{""name"":""Bahubali"",""yearOfRelease"":,""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":""1"",""producer"":1,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"Bahubali\",\"yearOfRelease\":\"2009-05-22T00:00:00\",\"plot\":,\"actors\":\"1\",\"ge" +
            "nres\":\"1\",\"producer\":1,\"poster\":\"C://Users/Kalyan/Downloads/Bahubali.png\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute(@"{""name"":""Bahubali"",""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":""1"",""producer"":1,""poster"":}", "400", new string[0])]
        [Xunit.InlineDataAttribute(@"{""name"":""Bahubali"",""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":""1"",""producer"":,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        [Xunit.InlineDataAttribute(@"{""name"":""Bahubali"",""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":,""producer"":1,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        [Xunit.InlineDataAttribute(@"{""name"":""Bahubali"",""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":,""genres"":""1"",""producer"":1,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        public void AddAMovie(string movie, string statusCode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PostMovie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Movie", movie);
            argumentsOfScenario.Add("status code", statusCode);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a Movie", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
 testRunner.When(string.Format("I make Post Request with \'{0}\' and \'api/Movies/\'", movie), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
 testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Update a Movie")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Update a Movie")]
        [Xunit.TraitAttribute("Category", "UpdateMovie")]
        [Xunit.InlineDataAttribute("1", @"{""Name"":""Bahubali"",""YearOfRelease"":""2009-05-22T00:00:00"",""Plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""Actors"":""1"",""Genres"":""1"",""ProducerId"":1,""Poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "200", new string[0])]
        [Xunit.InlineDataAttribute("1", @"{""name"":,""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":""1"",""producer"":1,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        [Xunit.InlineDataAttribute("1", @"{""name"":""Bahubali"",""yearOfRelease"":,""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":""1"",""producer"":1,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        [Xunit.InlineDataAttribute("1", "{\"name\":\"Bahubali\",\"yearOfRelease\":\"2009-05-22T00:00:00\",\"plot\":,\"actors\":\"1\",\"ge" +
            "nres\":\"1\",\"producer\":1,\"poster\":\"C://Users/Kalyan/Downloads/Bahubali.png\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("1", @"{""name"":""Bahubali"",""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":""1"",""producer"":1,""poster"":}", "400", new string[0])]
        [Xunit.InlineDataAttribute("1", @"{""name"":""Bahubali"",""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":""1"",""producer"":,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        [Xunit.InlineDataAttribute("1", @"{""name"":""Bahubali"",""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":,""producer"":1,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        [Xunit.InlineDataAttribute("9", @"{""name"":""Bahubali"",""yearOfRelease"":""2009-05-22T00:00:00"",""plot"":""A paralyzed former Marine joins the Avatar Program, a project that allows humans to remotely control genetically engineered  bodies, in order to infiltrate and stop the RDA corporation from mining a valuable mineral on their planet."",""actors"":""1"",""genres"":""1"",""producer"":1,""poster"":""C://Users/Kalyan/Downloads/Bahubali.png""}", "400", new string[0])]
        public void UpdateAMovie(string id, string movie, string statusCode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UpdateMovie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Id", id);
            argumentsOfScenario.Add("Movie", movie);
            argumentsOfScenario.Add("status code", statusCode);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update a Movie", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 38
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 39
 testRunner.When(string.Format("I make Update Request with \'{0}\' , \'{1}\' and \'api/Movies/\'", movie, id), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
 testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Delete a Movie")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Delete a Movie")]
        [Xunit.TraitAttribute("Category", "DeleteMovie")]
        [Xunit.InlineDataAttribute("1", "200", new string[0])]
        [Xunit.InlineDataAttribute("9", "400", new string[0])]
        public void DeleteAMovie(string id, string statusCode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DeleteMovie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Id", id);
            argumentsOfScenario.Add("status code", statusCode);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete a Movie", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 54
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 55
 testRunner.When(string.Format("I make Delete Request with \'{0}\' and \'api/Movies/\'", id), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 56
 testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                MovieResourceFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                MovieResourceFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
